### ISSUE TITLE
I get a 403 error when I GET.

### ISSUE THREAD

**Issue by splatterxl** [purrbot-site/ImageAPI#1]
### Expected behaviour
> What should happen?

I get the expected links and JSON

### Actual behaviour
> What happens instead?

I get a 403 error.

### Images/Links
> Please provide any screenshots/links that help describing your issue in more detail.

![image](https://user-images.githubusercontent.com/67709748/101540119-76265280-3997-11eb-8fc3-620c28d8105a.png)

**Comment by Andre601** [comment]
This issue seems more about the Image API, doesn't it?
What link did you try?

**Comment by splatterxl** [comment]
https://purrbot.site/api/sfw/slap/gif is what I tried, and sorry if I posted it in the wrong place.

**Comment by splatterxl** [comment]
And it works now.

**Comment by Andre601** [comment]
Yeah. I can't really tell what could've caused this issue. Only that it may happen at random points.

Also, the actual url would be https://purrbot.site/api/img/sfw/slap/gif

**Comment by splatterxl** [comment]
Ahhhhhhhhhh I figured that out after a while, thanks anyway.
